# frozen_string_literal: true

# generated by rails g statecraft:machine Shop::Order, kept as-is except the
# template's own commented example enabled — the namespaced runtime needs at
# least one edge to transition over.
class Shop::OrderFlow < ApplicationMachine
  state :pending, initial: true
  state :paid

  event :pay, from: :pending, to: :paid, guard: :payable?

  # Guards and callbacks resolve to instance methods of this class:

  private

  def payable?(record, metadata)
    metadata["amount"].to_i.positive?
  end
end
